name: PostgreSQL Extension Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PostgreSQL client and build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client postgresql-server-dev-16 build-essential

    - name: Install plv8 extension
      run: |
        wget https://github.com/plv8/plv8/archive/refs/tags/v3.2.2.tar.gz
        tar -xzf v3.2.2.tar.gz
        cd plv8-3.2.2
        make
        sudo make install

    - name: Install pgTAP
      run: |
        git clone https://github.com/theory/pgtap.git
        cd pgtap
        make
        sudo make install

    - name: Install extensions in database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "CREATE EXTENSION IF NOT EXISTS plv8;"
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "CREATE EXTENSION IF NOT EXISTS hstore;"
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "CREATE EXTENSION IF NOT EXISTS pgtap;"

    - name: Run test script
      run: |
        chmod +x test/runner.sh
        ./test/runner.sh --host localhost --user postgres --password postgres

    - name: Test Summary
      if: always()
      run: echo "Tests completed"
