name: PostgreSQL Extension Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: hankcp/postgres-ext:17.6
      env:
        POSTGRES_USER: postgres
        POSTGRES_HOST_AUTH_METHOD: trust
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start PostgreSQL
      run: |
        mkdir -p /var/lib/postgresql/data
        chown -R postgres:postgres /var/lib/postgresql/data
        gosu postgres /usr/lib/postgresql/17/bin/initdb -D /var/lib/postgresql/data
        gosu postgres /usr/lib/postgresql/17/bin/pg_ctl -D /var/lib/postgresql/data start -w

    - name: Install Postgres extension
      run: |
        pig ext add pgtap -y

    - name: Run test script
      run: |
        chmod +x test/runner.sh
        ./test/runner.sh --host localhost --user postgres

    - name: Test Summary
      if: always()
      run: echo "Tests completed"
